### ISSUE TITLE
Add log giving the uploaded filename

### ISSUE THREAD

**Issue by cyrilc-pro** [cyrilc-pro/jfrog-support-bundle-flunky#59]
The plugin uploads the SB ZIP file with a specific name that is hidden (unless DEBUG logs are enabled).

**Comment by ttetzlaff** [comment]
I think there should be basic INFO logs to follow what is happening. Currently everything is logged as DEBUG.

**Comment by cyrilc-pro** [comment]
Agreed. But some actions do not need to be logged as INFO (e.g. download and maybe even creation).
